CREATE TABLE [DOMetrics].[Proposal] (
    [ProposalId]                        BIGINT           NULL,
    [SolicitationApprovalStatus]        NVARCHAR (60)    NULL,
    [MeetsDollarsRaisedMajor]           INT              NOT NULL,
    [ProposalTitle]                     NVARCHAR (120)   NULL,
    [ProposalAskAmount]                 NUMERIC (14, 2)  NULL,
    [ProposalAskDate]                   DATETIME2 (7)    NULL,
    [ProposalStage]                     NVARCHAR (60)    NULL,
    [ProposalReceivedAmount]            NUMERIC (14, 2)  NULL,
    [ProposalCloseDate]                 DATETIME2 (7)    NULL,
    [DoRoleProposalAssignment]          NVARCHAR (60)    NULL,
    [IsProposalAssignmentActive]        NVARCHAR (1)     NULL,
    [AMMContactReportId]                BIGINT           NULL,
    [AMMContactDate]                    DATETIME2 (7)    NULL,
    [ContactAuthorName]                 NVARCHAR (60)    NULL,
    [ProspectId]                        BIGINT           NULL,
    [PrimaryEntityId]                   NVARCHAR (10)    NULL,
    [ProspectName]                      NVARCHAR (60)    NULL,
    [OverallStage]                      NVARCHAR (60)    NULL,
    [HighestCapacity]                   NVARCHAR (60)    NULL,
    [IsPrincipalGiftProspect]           INT              NULL,
    [IsChancellorsProspect]             INT              NULL,
    [OfficersProspectRole]              VARCHAR (1)      NOT NULL,
    [IsPmatsAssignmentActive]           INT              NOT NULL,
    [IsDevOfficerPmrAssignedToProspect] BIT              NULL,
    [DevOfficerName]                    NVARCHAR (35)    NULL,
    [DevOfficerUnit]                    NVARCHAR (40)    NULL,
    [DevOfficerUnitGroup]               NVARCHAR (40)    NULL,
    [ProspectSortName]                  NVARCHAR (60)    NULL,
    [DevOfficerId]                      NVARCHAR (10)    NULL,
    [IsDevOfficerAssignedToProspect]    BIT              NULL,
    [PmrAssignmentStartDate]            DATETIME2 (7)    NULL,
    [PmrAssignmentStopDate]             DATETIME2 (7)    NULL,
    [IsPMRAssignmentActive]             INT              NOT NULL,
    [IsDevOfficerAssignedToProposal]    BIT              NULL,
    [IsProspectActive]                  NVARCHAR (1)     NULL,
    [PmatsStartDate]                    DATETIME2 (7)    NULL,
    [PmatsStopDate]                     DATETIME2 (7)    NULL,
    [ProposalApprovalDate]              DATETIME2 (7)    NULL,
    [ProposalComment]                   NVARCHAR (4000)  NULL,
    [ProposalAssignmentStartDate]       DATETIME2 (7)    NULL,
    [ProposalAssignmentStopDate]        DATETIME2 (7)    NULL,
    [ContactAuthorId]                   NVARCHAR (10)    NULL,
    [ContactedEntityId]                 NVARCHAR (10)    NULL,
    [ContactedEntityName]               NVARCHAR (60)    NULL,
    [ContactedSortName]                 NVARCHAR (60)    NULL,
    [ContactReportAdded]                DATETIME2 (7)    NULL,
    [ContactTypeDesc]                   NVARCHAR (60)    NULL,
    [ContactPurposeDesc]                NVARCHAR (60)    NULL,
    [OtherContactTypeDesc]              NVARCHAR (60)    NULL,
    [MajorGiftQualified]                NVARCHAR (60)    NULL,
    [ContactDesc]                       NVARCHAR (120)   NULL,
    [ComprehensiveAsk]                  NVARCHAR (3)     NULL,
    [AskAmount]                         NVARCHAR (250)   NULL,
    [ContactReportAuditStatus]          NVARCHAR (60)    NULL,
    [ContactReportReviewDate]           DATETIME2 (7)    NULL,
    [AssignmentGUID]                    UNIQUEIDENTIFIER NOT NULL,
    [FiscalYear]                        CHAR (4)         NULL
);

