CREATE TABLE [DOMetrics].[tempProspectExport] (
    [ProspectId]                        BIGINT           NULL,
    [ProspectName]                      NVARCHAR (60)    NULL,
    [OverallStage]                      NVARCHAR (60)    NULL,
    [HighestCapacity]                   NVARCHAR (60)    NULL,
    [IsPrincipalGiftProspect]           INT              NOT NULL,
    [IsProspectChancellors]             INT              NOT NULL,
    [PrimaryEntityId]                   NVARCHAR (10)    NULL,
    [PmrAssignmentStartDate]            DATETIME2 (7)    NULL,
    [MetPmrAssignedGoodFaithEffort]     INT              NOT NULL,
    [MetPmrAssignedWithFaceToFace]      INT              NOT NULL,
    [IsPmrAssignedQualified]            INT              NOT NULL,
    [IsPmrAssignedDisqualified]         INT              NOT NULL,
    [IsPmrAssignedInProgress]           INT              NOT NULL,
    [CountPmrAssignedPhoneContacts]     INT              NOT NULL,
    [CountPmrAssignedEmailContacts]     INT              NOT NULL,
    [CountPmrAssignedContactAttempts]   INT              NOT NULL,
    [CountPmrAssignedSocialContacts]    INT              NOT NULL,
    [OfficerName]                       NVARCHAR (60)    NULL,
    [Unit]                              NVARCHAR (40)    NULL,
    [UnitGroup]                         NVARCHAR (40)    NULL,
    [ProspectSortName]                  NVARCHAR (60)    NULL,
    [DevOfficerId]                      NVARCHAR (10)    NULL,
    [IsProspectAssignedToOfficer]       BIT              NULL,
    [IsDevOfficerPmrAssignedToProspect] BIT              NULL,
    [PmrAssignmentStopDate]             DATETIME2 (7)    NULL,
    [IsPmrAssignmentActive]             INT              NOT NULL,
    [MeetsPmrAssigned]                  INT              NULL,
    [IsProspectActive]                  NVARCHAR (1)     NULL,
    [OfficersProspectRole]              NVARCHAR (60)    NULL,
    [PmatsAssignmentStartDate]          DATETIME2 (7)    NULL,
    [PmatsAssignmentStopDate]           DATETIME2 (7)    NULL,
    [IsPmatsAssignmentActive]           INT              NOT NULL,
    [AssignmentGUID]                    UNIQUEIDENTIFIER NOT NULL,
    [FiscalYear]                        CHAR (4)         NULL
);

