CREATE TABLE [DOMetrics].[tempContactReportExport] (
    [ReportId]                          BIGINT           NULL,
    [ContactDate]                       DATETIME2 (7)    NULL,
    [DateAdded]                         DATETIME2 (7)    NULL,
    [ContactType]                       NVARCHAR (60)    NULL,
    [ContactPurpose]                    NVARCHAR (60)    NULL,
    [OtherContactType]                  NVARCHAR (60)    NULL,
    [ContactDescription]                NVARCHAR (120)   NULL,
    [MajorGiftQualified]                NVARCHAR (60)    NULL,
    [ComprehensiveAsk]                  NVARCHAR (3)     NULL,
    [AskAmount]                         NVARCHAR (250)   NULL,
    [ResultOfAsk]                       NVARCHAR (60)    NULL,
    [ReceivedAmount]                    NVARCHAR (255)   NULL,
    [DateGiftBooked]                    NVARCHAR (60)    NULL,
    [ContactedEntityId]                 NVARCHAR (10)    NULL,
    [ContactedName]                     NVARCHAR (80)    NULL,
    [ProspectId]                        BIGINT           NULL,
    [ProspectName]                      NVARCHAR (60)    NULL,
    [OverallStage]                      NVARCHAR (60)    NULL,
    [HighestCapacity]                   NVARCHAR (60)    NULL,
    [IsPrincipalGiftProspect]           INT              NULL,
    [IsChancellorsProspect]             INT              NULL,
    [IsDevOfficerAssignedToProspect]    BIT              NULL,
    [IsDevOfficerPmrAssignedToProspect] BIT              NULL,
    [ProposalId]                        BIGINT           NULL,
    [SolicitationApprovalStatus]        NVARCHAR (60)    NULL,
    [ProposalStage]                     NVARCHAR (60)    NULL,
    [ProposalTitle]                     NVARCHAR (120)   NULL,
    [IsDevOfficerAssignedToProposal]    BIT              NULL,
    [DevOfficerName]                    NVARCHAR (60)    NULL,
    [DevOfficerUnit]                    NVARCHAR (40)    NULL,
    [DevOfficerUnitGroup]               NVARCHAR (40)    NULL,
    [ContactReportUnit]                 NVARCHAR (40)    NULL,
    [ContactReportUnitGroup]            NVARCHAR (40)    NULL,
    [ContactedSortName]                 NVARCHAR (80)    NULL,
    [DevOfficerId]                      NVARCHAR (10)    NULL,
    [PmrAssignmentStartDate]            DATETIME2 (7)    NULL,
    [PmrAssignmentStopDate]             DATETIME2 (7)    NULL,
    [AuthorName]                        NVARCHAR (60)    NULL,
    [AuthorId]                          NVARCHAR (10)    NULL,
    [IsProspectActive]                  NVARCHAR (1)     NULL,
    [AssignmentType]                    NVARCHAR (60)    NULL,
    [PmatsStartDate]                    DATETIME2 (7)    NULL,
    [PmatsStopDate]                     DATETIME2 (7)    NULL,
    [IsAssignmentActive]                NVARCHAR (1)     NULL,
    [ProposalApprovalDate]              DATETIME2 (7)    NULL,
    [ProposalComment]                   NVARCHAR (4000)  NULL,
    [ContactReportAuditStatus]          NVARCHAR (60)    NULL,
    [ContactReportReviewDate]           DATETIME2 (7)    NULL,
    [ContactReportGUID]                 UNIQUEIDENTIFIER NOT NULL,
    [FiscalYear]                        VARCHAR (4)      NOT NULL,
    [IsFaceToFace]                      INT              NOT NULL,
    [IsAskMadeMajor]                    INT              NOT NULL,
    [IsAskMadeAnnualSpecial]            INT              NOT NULL,
    [IsDollarsRaisedAnnual]             INT              NOT NULL,
    [IsComprehensiveAsk]                INT              NOT NULL,
    [IsFacultyInteraction]              INT              NOT NULL,
    [ProspectSortName]                  NVARCHAR (60)    NULL
);

